# Generated by Django 5.1.4 on 2025-01-04 16:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('include_contact_details', models.BooleanField(default=False, help_text='Include contact details at the bottom of the page.')),
                ('main_content', wagtail.fields.RichTextField(blank=True)),
                ('core_team', wagtail.fields.StreamField([('core_team_member', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('image', 1)]], {})})),
                ('board_members', wagtail.fields.StreamField([('board_member', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 0)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('include_contact_details', models.BooleanField(default=False, help_text='Include contact details at the bottom of the page.')),
                ('main_content', wagtail.fields.RichTextField(blank=True)),
                ('forms', wagtail.fields.StreamField([('form', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('document', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('include_contact_details', models.BooleanField(default=False, help_text='Include contact details at the bottom of the page.')),
                ('main_content', wagtail.fields.RichTextField(blank=True)),
                ('accordions', wagtail.fields.StreamField([('accordion_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {})}, help_text='These are good for adding collapsible content to the page, like FAQs or other content that can be grouped together.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_image_alt_text', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('include_contact_details', models.BooleanField(default=False, help_text='Include contact details at the bottom of the page.')),
                ('main_content', wagtail.fields.RichTextField(blank=True)),
                ('cta_cards', wagtail.fields.StreamField([('cta_card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('page', 1), ('background_image', 2), ('alt_text', 0)]], {})})),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
