# Generated by Django 5.1.4 on 2025-01-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="menu_sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="formspage",
            name="menu_sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="menu_sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="homepage",
            name="menu_sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
