# Generated by Django 5.1.4 on 2025-01-14 13:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_menu_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpage',
            name='cta_cards',
            field=wagtail.fields.StreamField([('cta_card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('page', 1), ('background_image', 2), ('alt_text', 0)]], {})}, help_text='These are good for adding links to other pages on the site.'),
        ),
    ]
