# Generated by Django 5.1.4 on 2025-01-14 13:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_generalpage_cta_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='core_team',
            field=wagtail.fields.StreamField([('core_team_member', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.EmailBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('role', 1), ('email', 2)]], {})}),
        ),
    ]
