# Generated by Django 5.1.4 on 2025-01-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_aboutpage_core_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpage',
            name='accordions',
        ),
    ]
